spring.application.name=chinvat

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${SERVER_PORT:8080}
spring.jackson.time-zone=${APP_TIME_ZONE:UTC}
management.endpoints.web.exposure.include=health,info,metrics

